# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb4cdf4baeb0c3656769b8701999343d526030401bc52595747bc13188ad4f381b0cc5bdd46d83cbca60d7bae7054bbd5710b80621d942aa879aca149d0d0560

test:
  secret_key_base: 348e06c3c883ad10f4d809fa8b0408c241faf9682a5e33a7edd173af25a27359b5abb32d5592b2c7362beffa10e17be03723ff25c9ac14aa59fd4a7f4be6f131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
